package state

import (
	"fmt"
	"regexp"
)

// storyIDPattern constrains story IDs to a safe charset. Story IDs are
// generated by LLMs (the Tech Lead decomposes requirements into stories, and
// the escalation chain splits/re-plans them). Per the project's trust model
// (see CLAUDE.md "Prompt Injection Defenses"), LLM output is untrusted data.
//
// Story IDs flow into git branch names (`vxd/<id>`), git refs, and filesystem
// paths (`filepath.Join(worktreeBase, <id>)`). Without validation, an ID
// containing `/`, `..`, whitespace, or a leading `-` enables path traversal
// (escaping the worktrees directory) and argument injection into git commands.
//
// The allowed charset (alphanumeric, dot, underscore, hyphen) mirrors
// runtime.ValidateSessionName and cannot express a path separator or a
// parent-directory reference.
var storyIDPattern = regexp.MustCompile(`^[a-zA-Z0-9._-]+$`)

// maxStoryIDLen bounds the ID length to keep branch names and path components
// within filesystem limits and avoid pathological LLM output.
const maxStoryIDLen = 128

// ValidateStoryID checks that a story ID contains only safe characters and is
// usable as a git ref component and filesystem path segment. It rejects empty
// strings, overly long IDs, path-traversal sequences, and any name containing
// shell/path metacharacters.
//
// It additionally rejects "." and ".." outright (which the charset permits as
// standalone strings) because they are invalid path components.
func ValidateStoryID(id string) error {
	if id == "" {
		return fmt.Errorf("story ID must not be empty")
	}
	if len(id) > maxStoryIDLen {
		return fmt.Errorf("story ID %q exceeds %d characters", id, maxStoryIDLen)
	}
	if id == "." || id == ".." {
		return fmt.Errorf("story ID %q is not a valid path component", id)
	}
	// Reject a leading hyphen: such an ID would be interpreted as a flag when
	// passed as a positional argument to git/tmux (argument injection), even
	// though the charset itself permits hyphens internally.
	if id[0] == '-' {
		return fmt.Errorf("story ID %q must not start with a hyphen", id)
	}
	if !storyIDPattern.MatchString(id) {
		return fmt.Errorf("story ID %q contains invalid characters (allowed: a-z A-Z 0-9 . _ -)", id)
	}
	return nil
}
