package docker

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/tzone85/vortex-dispatch/internal/devdb"
)

// Config configures the Docker provider.
type Config struct {
	Image          string
	ContainerName  string
	TemplateVolume string
	Network        string
	HostPortRange  string
	AdminUser      string
	AdminPassword  string // resolved or generated by EnsureContainer (Task 18)
	HostPort       int    // resolved by EnsureContainer from HostPortRange
	Host           string // DB host for DSN (default "localhost"); override for Colima/VM setups
}

// Provider implements devdb.Provider against a local Docker daemon.
type Provider struct {
	client *Client
	cfg    Config
	mu     sync.Mutex // guards lazy bootstrap state (dsn, AdminPassword, HostPort)
	dsn    string     // admin DSN; empty until EnsureContainer succeeds
	ports  *Allocator
}

// NewProvider returns a non-bootstrapped Provider. EnsureContainer (Task 18)
// runs lazily on first Create/Fork/etc. so unit tests do not need Docker.
func NewProvider(cfg Config) *Provider {
	cfg = applyDefaults(cfg)
	a, _ := NewAllocator(cfg.HostPortRange) // empty/invalid range surfaces later on Acquire
	return &Provider{
		client: NewClient(ClientConfig{}),
		cfg:    cfg,
		ports:  a,
	}
}

// NewProviderWithClient is like NewProvider but lets callers inject a custom
// HTTP client (used by tests to mock the Docker daemon).
func NewProviderWithClient(cfg Config, client *Client) *Provider {
	cfg = applyDefaults(cfg)
	a, _ := NewAllocator(cfg.HostPortRange)
	return &Provider{client: client, cfg: cfg, ports: a}
}

func applyDefaults(c Config) Config {
	if c.Image == "" {
		c.Image = "postgres:16"
	}
	if c.ContainerName == "" {
		c.ContainerName = "vxd-devdb-pg16"
	}
	if c.Network == "" {
		c.Network = "vxd-devdb"
	}
	if c.HostPortRange == "" {
		c.HostPortRange = "5500-5599"
	}
	if c.AdminUser == "" {
		c.AdminUser = "postgres"
	}
	if c.TemplateVolume == "" {
		home, _ := os.UserHomeDir()
		c.TemplateVolume = filepath.Join(home, ".vxd", "devdb-data")
	}
	if c.Host == "" {
		c.Host = "localhost"
	}
	return c
}

// bindIPForHost decides which host interface the container's Postgres port
// should bind to, based on the configured DB host.
//
// For the default loopback host (localhost / 127.0.0.1 / ::1 / empty) the port
// binds to 127.0.0.1 only, so the dev database is not reachable from the LAN.
// For an explicit non-loopback host — a Colima/Lima VM IP, where the operator
// deliberately connects across the VM boundary — it binds to 0.0.0.0 so that
// cross-host access keeps working.
func bindIPForHost(host string) string {
	switch host {
	case "", "localhost", "127.0.0.1", "::1":
		return "127.0.0.1"
	default:
		return "0.0.0.0"
	}
}

// Name returns "docker".
func (p *Provider) Name() string { return "docker" }

// Ping checks the Docker daemon is reachable.
func (p *Provider) Ping(ctx context.Context) error {
	return p.client.Ping(ctx)
}

// EnsureContainer is idempotent: it boots the network, container, and waits
// for pg. First Create/Fork/etc. call invokes this. Safe to call multiple
// times; later calls are no-ops if the container is already running.
func (p *Provider) EnsureContainer(ctx context.Context) error {
	if err := p.client.Ping(ctx); err != nil {
		return err
	}
	if err := p.client.EnsureNetwork(ctx, p.cfg.Network); err != nil {
		return err
	}

	pw, err := p.loadOrCreateAdminPassword(filepath.Dir(p.cfg.TemplateVolume))
	if err != nil {
		return err
	}
	p.cfg.AdminPassword = pw

	state, err := p.client.InspectContainer(ctx, p.cfg.ContainerName)
	if err != nil {
		return err
	}
	if !state.Exists {
		port, err := p.ports.Acquire()
		if err != nil {
			return err
		}
		p.cfg.HostPort = port
		spec := CreateContainerSpec{
			Name:          p.cfg.ContainerName,
			Image:         p.cfg.Image,
			HostPort:      port,
			VolumeMount:   p.cfg.TemplateVolume,
			AdminPassword: pw,
			Network:       p.cfg.Network,
			HostBindIP:    bindIPForHost(p.cfg.Host),
		}
		id, err := p.client.CreateContainer(ctx, spec)
		if err != nil {
			return err
		}
		if err := p.client.StartContainer(ctx, id); err != nil {
			return err
		}
	} else if !state.Running {
		if err := p.client.StartContainer(ctx, p.cfg.ContainerName); err != nil {
			return err
		}
	}

	// If the container already existed and was running, p.cfg.HostPort may
	// still be zero. In that case fall back to the lowest port in the
	// allocator's range — the container's port binding is fixed at creation,
	// so the first port in our range is a reasonable default. (Real
	// production deployments persist this in the future; out of scope here.)
	if p.cfg.HostPort == 0 {
		port, err := p.ports.Acquire()
		if err != nil {
			return err
		}
		p.cfg.HostPort = port
	}

	p.mu.Lock()
	p.dsn = fmt.Sprintf("postgres://%s:%s@%s:%d/postgres?sslmode=disable",
		p.cfg.AdminUser, pw, p.cfg.Host, p.cfg.HostPort)
	p.mu.Unlock()
	return nil
}

// Create provisions an empty DB inside the host container.
func (p *Provider) Create(ctx context.Context, opts devdb.CreateOpts) (devdb.DB, error) {
	if !devdb.IsValid(opts.Name) {
		return devdb.DB{}, fmt.Errorf("%w: %q", devdb.ErrInvalidName, opts.Name)
	}
	pg, err := p.adminConn(ctx)
	if err != nil {
		return devdb.DB{}, err
	}
	defer pg.Close(ctx)
	if err := pg.CreateDB(ctx, opts.Name); err != nil {
		return devdb.DB{}, fmt.Errorf("docker create: %w", err)
	}
	return p.dbFromName(opts), nil
}

// Fork copies a template DB inside the host container.
func (p *Provider) Fork(ctx context.Context, template string, opts devdb.CreateOpts) (devdb.DB, error) {
	if !devdb.IsValid(opts.Name) {
		return devdb.DB{}, fmt.Errorf("%w: %q", devdb.ErrInvalidName, opts.Name)
	}
	pg, err := p.adminConn(ctx)
	if err != nil {
		return devdb.DB{}, err
	}
	defer pg.Close(ctx)

	// Mark the source as a template (idempotent — Postgres tolerates UPDATE
	// of datistemplate to its current value).
	if err := pg.SetTemplateFlag(ctx, template, true); err != nil {
		return devdb.DB{}, fmt.Errorf("docker mark template: %w", err)
	}
	if err := pg.CreateDBFromTemplate(ctx, opts.Name, template); err != nil {
		return devdb.DB{}, fmt.Errorf("docker fork: %w", err)
	}
	return p.dbFromName(opts), nil
}

// Delete drops the DB after terminating active connections.
// dbID is the DB name in this provider (the docker provider has no separate
// opaque ID space).
func (p *Provider) Delete(ctx context.Context, dbID string) error {
	pg, err := p.adminConn(ctx)
	if err != nil {
		return err
	}
	defer pg.Close(ctx)
	if err := pg.KillConnections(ctx, dbID); err != nil {
		return fmt.Errorf("docker kill conns %s: %w", dbID, err)
	}
	if err := pg.DropDB(ctx, dbID); err != nil {
		return fmt.Errorf("docker drop %s: %w", dbID, err)
	}
	return nil
}

func (p *Provider) dbFromName(opts devdb.CreateOpts) devdb.DB {
	dsn := p.dbDSN(opts.Name, false)
	var ro string
	if opts.ReadOnly {
		ro = p.dbDSN(opts.Name, true)
	}
	return devdb.DB{
		ID:               opts.Name,
		Name:             opts.Name,
		Provider:         "docker",
		ConnectionString: dsn,
		ReadOnlyDSN:      ro,
		Labels:           opts.Labels,
	}
}

func (p *Provider) dbDSN(name string, readonly bool) string {
	dsn := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable",
		p.cfg.AdminUser, p.cfg.AdminPassword, p.cfg.Host, p.cfg.HostPort, name)
	if readonly {
		dsn += "&options=-c%20default_transaction_read_only%3Don"
	}
	return dsn
}

// adminConn returns a pgx connection to the host container's admin DB.
// If the provider has not been bootstrapped yet it calls EnsureContainer first.
func (p *Provider) adminConn(ctx context.Context) (*PGConn, error) {
	p.mu.Lock()
	dsn := p.dsn
	p.mu.Unlock()
	if dsn == "" {
		if err := p.EnsureContainer(ctx); err != nil {
			return nil, err
		}
		p.mu.Lock()
		dsn = p.dsn
		p.mu.Unlock()
	}
	return ConnectPG(ctx, dsn)
}

// List returns all DBs in the host container with the VXD prefix.
func (p *Provider) List(ctx context.Context) ([]devdb.DB, error) {
	pg, err := p.adminConn(ctx)
	if err != nil {
		return nil, err
	}
	defer pg.Close(ctx)
	names, err := pg.ListDBsWithPrefix(ctx, devdb.PrefixVXD+"-")
	if err != nil {
		return nil, fmt.Errorf("docker list: %w", err)
	}
	out := make([]devdb.DB, 0, len(names))
	for _, n := range names {
		out = append(out, p.dbFromName(devdb.CreateOpts{Name: n}))
	}
	return out, nil
}

// Schema returns a text dump of the named DB's schema.
func (p *Provider) Schema(ctx context.Context, dbID string) (string, error) {
	dsn := p.dbDSN(dbID, false)
	pg, err := ConnectPG(ctx, dsn)
	if err != nil {
		return "", err
	}
	defer pg.Close(ctx)
	return DumpSchema(ctx, pg)
}

// loadOrCreateAdminPassword reads <storageDir>/devdb-admin.pw if present (mode 0600),
// otherwise generates a new 32-char hex password and writes it.
// storageDir lets tests override the location (production uses Config.TemplateVolume's parent).
func (p *Provider) loadOrCreateAdminPassword(storageDir string) (string, error) {
	path := filepath.Join(storageDir, "devdb-admin.pw")
	if b, err := os.ReadFile(path); err == nil {
		return string(b), nil
	}
	var seed [16]byte
	if _, err := rand.Read(seed[:]); err != nil {
		return "", err
	}
	pw := hex.EncodeToString(seed[:])
	if err := os.MkdirAll(storageDir, 0o700); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(pw), 0o600); err != nil {
		return "", err
	}
	return pw, nil
}
