package docker

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/tzone85/vortex-dispatch/internal/devdb"
)

// Config configures the Docker provider.
type Config struct {
	Image          string
	ContainerName  string
	TemplateVolume string
	Network        string
	HostPortRange  string
	AdminUser      string
	AdminPassword  string // resolved or generated by EnsureContainer (Task 18)
	HostPort       int    // resolved by EnsureContainer from HostPortRange
}

// Provider implements devdb.Provider against a local Docker daemon.
type Provider struct {
	client *Client
	cfg    Config
	mu     sync.Mutex // guards lazy bootstrap state (dsn, AdminPassword, HostPort)
	dsn    string     // admin DSN; empty until EnsureContainer succeeds
	ports  *Allocator
}

// NewProvider returns a non-bootstrapped Provider. EnsureContainer (Task 18)
// runs lazily on first Create/Fork/etc. so unit tests do not need Docker.
func NewProvider(cfg Config) *Provider {
	cfg = applyDefaults(cfg)
	a, _ := NewAllocator(cfg.HostPortRange) // empty/invalid range surfaces later on Acquire
	return &Provider{
		client: NewClient(ClientConfig{}),
		cfg:    cfg,
		ports:  a,
	}
}

func applyDefaults(c Config) Config {
	if c.Image == "" {
		c.Image = "postgres:16"
	}
	if c.ContainerName == "" {
		c.ContainerName = "vxd-devdb-pg16"
	}
	if c.Network == "" {
		c.Network = "vxd-devdb"
	}
	if c.HostPortRange == "" {
		c.HostPortRange = "5500-5599"
	}
	if c.AdminUser == "" {
		c.AdminUser = "postgres"
	}
	if c.TemplateVolume == "" {
		home, _ := os.UserHomeDir()
		c.TemplateVolume = filepath.Join(home, ".vxd", "devdb-data")
	}
	return c
}

// Name returns "docker".
func (p *Provider) Name() string { return "docker" }

// Ping checks the Docker daemon is reachable.
func (p *Provider) Ping(ctx context.Context) error {
	return p.client.Ping(ctx)
}

// Create provisions an empty DB inside the host container.
func (p *Provider) Create(ctx context.Context, opts devdb.CreateOpts) (devdb.DB, error) {
	if !devdb.IsValid(opts.Name) {
		return devdb.DB{}, fmt.Errorf("%w: %q", devdb.ErrInvalidName, opts.Name)
	}
	pg, err := p.adminConn(ctx)
	if err != nil {
		return devdb.DB{}, err
	}
	defer pg.Close(ctx)
	if err := pg.CreateDB(ctx, opts.Name); err != nil {
		return devdb.DB{}, fmt.Errorf("docker create: %w", err)
	}
	return p.dbFromName(opts), nil
}

// Fork copies a template DB inside the host container.
func (p *Provider) Fork(ctx context.Context, template string, opts devdb.CreateOpts) (devdb.DB, error) {
	if !devdb.IsValid(opts.Name) {
		return devdb.DB{}, fmt.Errorf("%w: %q", devdb.ErrInvalidName, opts.Name)
	}
	pg, err := p.adminConn(ctx)
	if err != nil {
		return devdb.DB{}, err
	}
	defer pg.Close(ctx)

	// Mark the source as a template (idempotent — Postgres tolerates UPDATE
	// of datistemplate to its current value).
	if err := pg.SetTemplateFlag(ctx, template, true); err != nil {
		return devdb.DB{}, fmt.Errorf("docker mark template: %w", err)
	}
	if err := pg.CreateDBFromTemplate(ctx, opts.Name, template); err != nil {
		return devdb.DB{}, fmt.Errorf("docker fork: %w", err)
	}
	return p.dbFromName(opts), nil
}

// Delete drops the DB after terminating active connections.
// dbID is the DB name in this provider (the docker provider has no separate
// opaque ID space).
func (p *Provider) Delete(ctx context.Context, dbID string) error {
	pg, err := p.adminConn(ctx)
	if err != nil {
		return err
	}
	defer pg.Close(ctx)
	if err := pg.KillConnections(ctx, dbID); err != nil {
		return fmt.Errorf("docker kill conns %s: %w", dbID, err)
	}
	if err := pg.DropDB(ctx, dbID); err != nil {
		return fmt.Errorf("docker drop %s: %w", dbID, err)
	}
	return nil
}

func (p *Provider) dbFromName(opts devdb.CreateOpts) devdb.DB {
	dsn := p.dbDSN(opts.Name, false)
	var ro string
	if opts.ReadOnly {
		ro = p.dbDSN(opts.Name, true)
	}
	return devdb.DB{
		ID:               opts.Name,
		Name:             opts.Name,
		Provider:         "docker",
		ConnectionString: dsn,
		ReadOnlyDSN:      ro,
		Labels:           opts.Labels,
	}
}

func (p *Provider) dbDSN(name string, readonly bool) string {
	dsn := fmt.Sprintf("postgres://%s:%s@localhost:%d/%s?sslmode=disable",
		p.cfg.AdminUser, p.cfg.AdminPassword, p.cfg.HostPort, name)
	if readonly {
		dsn += "&options=-c%20default_transaction_read_only%3Don"
	}
	return dsn
}

// adminConn returns a pgx connection to the host container's admin DB.
// Lazy bootstrap lands in Task 18 (EnsureContainer); for now a Provider that
// has never been bootstrapped returns ErrProviderDown so unit tests can
// exercise the error path.
func (p *Provider) adminConn(ctx context.Context) (*PGConn, error) {
	p.mu.Lock()
	dsn := p.dsn
	p.mu.Unlock()
	if dsn == "" {
		return nil, fmt.Errorf("docker provider not bootstrapped: %w", devdb.ErrProviderDown)
	}
	return ConnectPG(ctx, dsn)
}

// List is implemented in Task 17.
func (p *Provider) List(ctx context.Context) ([]devdb.DB, error) {
	return nil, fmt.Errorf("docker.Provider.List: not yet implemented (Task 17): %w", devdb.ErrUnsupported)
}

// Schema is implemented in Task 17.
func (p *Provider) Schema(ctx context.Context, dbID string) (string, error) {
	return "", fmt.Errorf("docker.Provider.Schema: not yet implemented (Task 17): %w", devdb.ErrUnsupported)
}
