package engine

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tzone85/vortex-dispatch/internal/llm"
)

// Factory documentation standard. A completed requirement ships a full,
// consistent documentation set:
//
//   - README.md                  — the entry point
//   - docs/architecture.svg      — rendered SVG (handled by svg_docs.go)
//   - docs/sequence.svg          — rendered SVG (handled by svg_docs.go)
//   - docs/training.md           — a getting-started tutorial
//   - docs/adr/0001-*.md …       — Architecture Decision Records
//   - docs/adr/README.md         — ADR index
//   - docs/README.md             — documentation index
//
// The scribe story instructs the coding agent to produce all of this, but agents
// are inconsistent. These post-merge backstops make the standard hold by
// construction: the docs index is generated deterministically from whatever
// docs/ contains, and the training guide + ADRs are generated by the doc model
// only when the agent did not already supply them. Every backstop is
// best-effort and never blocks requirement completion.

// ensureFactoryDocs runs all comprehensive-documentation backstops. SVG diagrams
// and the README are handled separately (earlier) in generateDocumentation; this
// fills in training, ADRs, and the docs index.
func ensureFactoryDocs(ctx context.Context, repoDir, reqTitle, fileTree, projectInfo string, client llm.Client, model string) {
	ensureTrainingGuide(ctx, repoDir, reqTitle, fileTree, projectInfo, client, model)
	ensureADRs(ctx, repoDir, reqTitle, fileTree, projectInfo, client, model)
	// The index is generated last so it reflects every doc the others produced.
	ensureDocsIndex(repoDir)
}

// --- Deterministic docs index ------------------------------------------------

// ensureDocsIndex (re)generates docs/README.md as an index of everything in
// docs/. Pure-deterministic, no LLM — so the index always exists and is current.
func ensureDocsIndex(repoDir string) {
	docsDir := filepath.Join(repoDir, "docs")
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		return // no docs/ directory — nothing to index
	}

	var diagrams, guides []string
	hasADRs := false
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() {
			if name == "adr" {
				hasADRs = true
			}
			continue
		}
		if name == "README.md" {
			continue // the index itself
		}
		switch {
		case strings.HasSuffix(name, ".svg"):
			diagrams = append(diagrams, name)
		case strings.HasSuffix(name, ".md"):
			guides = append(guides, name)
		}
	}

	index := buildDocsIndex(diagrams, guides, hasADRs)
	if err := os.WriteFile(filepath.Join(docsDir, "README.md"), []byte(index), 0o644); err != nil {
		log.Printf("[docs] write docs/README.md index failed: %v", err)
	}
}

// buildDocsIndex renders the docs index markdown. Pure function — unit-pinned.
func buildDocsIndex(diagrams, guides []string, hasADRs bool) string {
	sort.Strings(diagrams)
	sort.Strings(guides)

	var b strings.Builder
	b.WriteString("# Documentation\n\n")
	b.WriteString("Documentation index. Start with the [project README](../README.md).\n")

	if len(guides) > 0 {
		b.WriteString("\n## Guides\n\n")
		for _, g := range guides {
			fmt.Fprintf(&b, "- [%s](%s)\n", humanizeDocName(g), g)
		}
	}
	if len(diagrams) > 0 {
		b.WriteString("\n## Diagrams\n\n")
		for _, d := range diagrams {
			fmt.Fprintf(&b, "- [%s](%s)\n", humanizeDocName(d), d)
		}
	}
	if hasADRs {
		b.WriteString("\n## Architecture Decision Records\n\n")
		b.WriteString("- [ADR index](adr/README.md)\n")
	}
	return b.String()
}

// humanizeDocName turns "training.md" / "architecture.svg" into "Training" /
// "Architecture" for index link text.
func humanizeDocName(name string) string {
	base := strings.TrimSuffix(strings.TrimSuffix(name, ".md"), ".svg")
	base = strings.NewReplacer("-", " ", "_", " ").Replace(base)
	fields := strings.Fields(base)
	for i, f := range fields {
		if f == "" {
			continue
		}
		fields[i] = strings.ToUpper(f[:1]) + f[1:]
	}
	return strings.Join(fields, " ")
}

// --- Training guide backstop (LLM) -------------------------------------------

func ensureTrainingGuide(ctx context.Context, repoDir, reqTitle, fileTree, projectInfo string, client llm.Client, model string) {
	trainingPath := filepath.Join(repoDir, "docs", "training.md")
	if fileExistsNonEmpty(trainingPath) {
		return // agent already wrote it
	}

	prompt := fmt.Sprintf(`Write a "Getting Started" tutorial (docs/training.md) for this software project, accurate to the code.

PROJECT: %s

MANIFEST (truncated):
%s

FILE TREE (truncated):
%s

Requirements:
- A hands-on walkthrough that takes a new user from install/setup to a working result.
- Copy-pasteable commands and the expected output shape, grounded in what the project actually does (real commands/endpoints/flags — do not invent).
- Markdown only. Output ONLY the file content, no commentary, no code fences around the whole document.`,
		reqTitle, truncateForPrompt(projectInfo, 1500), truncateForPrompt(fileTree, 1800))

	resp, err := client.Complete(ctx, llm.CompletionRequest{
		Model:     model,
		Messages:  []llm.Message{{Role: llm.RoleUser, Content: prompt}},
		MaxTokens: 4000,
	})
	if err != nil {
		log.Printf("[docs] training guide generation failed: %v", err)
		return
	}
	content := stripMarkdownFences(strings.TrimSpace(resp.Content))
	if len(content) < 80 {
		log.Printf("[docs] training guide too short (%d bytes), skipping", len(content))
		return
	}
	if err := os.MkdirAll(filepath.Dir(trainingPath), 0o755); err != nil {
		log.Printf("[docs] mkdir docs for training failed: %v", err)
		return
	}
	if err := os.WriteFile(trainingPath, []byte(content+"\n"), 0o644); err != nil {
		log.Printf("[docs] write training.md failed: %v", err)
		return
	}
	log.Printf("[docs] generated docs/training.md (%d bytes)", len(content))
}

// fileExistsNonEmpty reports whether path exists and has non-whitespace content.
func fileExistsNonEmpty(path string) bool {
	data, err := os.ReadFile(path)
	return err == nil && len(strings.TrimSpace(string(data))) > 0
}
