package engine

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const waveContextFileName = "WAVE_CONTEXT.md"

// CaptureStoryContext extracts a summary of what a completed story built
// and appends it to the wave context document in the repo root.
// This document is read by subsequent stories so they know what prior
// stories accomplished — preventing blind implementation and conflicting patterns.
func CaptureStoryContext(repoDir, storyID, storyTitle, branch string) {
	// Get the list of files that were added or modified
	filesChanged := runGitSafe(repoDir, "diff", "--name-only", "main..."+branch)
	if filesChanged == "" {
		// Fallback: get from last commit
		filesChanged = runGitSafe(repoDir, "diff", "--name-only", "HEAD~1..HEAD")
	}

	// Extract function/type signatures from changed Go files for richer context
	signatures := extractSignatures(repoDir, filesChanged)

	// Build the context entry
	entry := fmt.Sprintf(`
### %s: %s

**Files changed:**
%s

`, storyID, storyTitle, formatFileList(filesChanged))

	if signatures != "" {
		entry += fmt.Sprintf("**Key definitions:**\n```\n%s\n```\n\n", signatures)
	}

	// Append to the wave context file
	contextPath := filepath.Join(repoDir, waveContextFileName)
	appendToWaveContext(contextPath, storyID, entry)
}

// ReadWaveContext reads the current wave context document from a worktree.
// Returns empty string if no context exists yet (first story in the requirement).
func ReadWaveContext(worktreePath string) string {
	// Check in the worktree itself
	contextPath := filepath.Join(worktreePath, waveContextFileName)
	data, err := os.ReadFile(contextPath)
	if err != nil {
		return ""
	}
	content := string(data)
	// Truncate if too large (keep most recent stories)
	if len(content) > 4000 {
		content = content[len(content)-4000:]
		// Find the first story header after truncation point
		idx := strings.Index(content, "### ")
		if idx > 0 {
			content = content[idx:]
		}
		content = "... (earlier stories truncated)\n\n" + content
	}
	return content
}

// appendToWaveContext creates or appends to the wave context file.
func appendToWaveContext(path, storyID, entry string) {
	var content string

	if data, err := os.ReadFile(path); err == nil {
		content = string(data)
	} else {
		content = "# Wave Context — What Prior Stories Built\n\nThis document is auto-generated by VXD to help subsequent stories\nunderstand what was already implemented.\n\n"
	}

	// Don't duplicate if this story is already documented
	if strings.Contains(content, storyID+":") {
		return
	}

	content += entry

	// #nosec G703 -- path is <worktree>/WAVE_CONTEXT.md; the worktree root comes from vxd's own executor, not user input
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		log.Printf("[wave-context] failed to write %s: %v", path, err)
	}
}

// extractSignatures finds exported function and type declarations in changed Go files.
func extractSignatures(repoDir, filesChanged string) string {
	var sigs []string
	for _, file := range strings.Split(filesChanged, "\n") {
		file = strings.TrimSpace(file)
		if file == "" || !strings.HasSuffix(file, ".go") || strings.HasSuffix(file, "_test.go") {
			continue
		}

		fullPath := filepath.Join(repoDir, file)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			continue
		}

		for _, line := range strings.Split(string(data), "\n") {
			trimmed := strings.TrimSpace(line)
			// Capture exported function signatures and type declarations
			if strings.HasPrefix(trimmed, "func ") && strings.Contains(trimmed, "(") {
				// Only exported functions (uppercase first letter after "func ")
				name := extractFuncName(trimmed)
				if name != "" && name[0] >= 'A' && name[0] <= 'Z' {
					sig := trimmed
					if idx := strings.Index(sig, "{"); idx > 0 {
						sig = strings.TrimSpace(sig[:idx])
					}
					sigs = append(sigs, fmt.Sprintf("%s: %s", file, sig))
				}
			} else if strings.HasPrefix(trimmed, "type ") && (strings.Contains(trimmed, "struct") || strings.Contains(trimmed, "interface")) {
				sigs = append(sigs, fmt.Sprintf("%s: %s", file, trimmed))
			}
		}

		if len(sigs) > 30 { // Cap to prevent context bloat
			break
		}
	}

	return strings.Join(sigs, "\n")
}

func extractFuncName(funcLine string) string {
	// "func FooBar(x int) error" → "FooBar"
	// "func (s *Store) Get(key string)" → "Get"
	line := strings.TrimPrefix(funcLine, "func ")
	if strings.HasPrefix(line, "(") {
		// Method: skip receiver
		closeIdx := strings.Index(line, ")")
		if closeIdx < 0 {
			return ""
		}
		line = strings.TrimSpace(line[closeIdx+1:])
	}
	parenIdx := strings.Index(line, "(")
	if parenIdx < 0 {
		return ""
	}
	return strings.TrimSpace(line[:parenIdx])
}

func formatFileList(filesChanged string) string {
	var lines []string
	for _, f := range strings.Split(filesChanged, "\n") {
		f = strings.TrimSpace(f)
		if f != "" {
			lines = append(lines, "- `"+f+"`")
		}
	}
	if len(lines) == 0 {
		return "- (no files detected)"
	}
	return strings.Join(lines, "\n")
}

func runGitSafe(dir string, args ...string) string {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, _ := cmd.Output()
	return strings.TrimSpace(string(out))
}
