package improve

import (
	"context"
	"fmt"
	"log"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
)

// ImplementResult holds the outcome of implementing a single finding.
type ImplementResult struct {
	Finding      AnalyzedFinding
	Branch       string
	PRURL        string
	Disposition  string // implemented, proposed, aborted
	TestsPassed  bool
	FilesChanged int
	LinesChanged int
	Error        string
}

// IsImplemented returns true if the finding was successfully implemented.
func (r ImplementResult) IsImplemented() bool {
	return r.Disposition == "implemented"
}

// Implementer creates branches, invokes Claude, runs quality gates, and opens PRs.
type Implementer struct {
	repoPath   string
	claudePath string
	maxDiff    int
	maxFiles   int
	dryRun     bool
}

// NewImplementer creates an implementer with the given constraints.
func NewImplementer(repoPath, claudePath string, maxDiff, maxFiles int, dryRun bool) *Implementer {
	return &Implementer{
		repoPath:   repoPath,
		claudePath: claudePath,
		maxDiff:    maxDiff,
		maxFiles:   maxFiles,
		dryRun:     dryRun,
	}
}

// Implement attempts to implement a single analyzed finding.
func (impl *Implementer) Implement(ctx context.Context, finding AnalyzedFinding, date string) ImplementResult {
	result := ImplementResult{Finding: finding}

	slug := slugify(finding.Title)
	branch := fmt.Sprintf("vxd-improve/%s-%s", date, slug)
	result.Branch = branch

	if impl.dryRun {
		result.Disposition = "proposed"
		return result
	}

	if err := impl.git("checkout", "-b", branch, "main"); err != nil {
		result.Disposition = "aborted"
		result.Error = fmt.Sprintf("create branch: %v", err)
		impl.git("checkout", "main")
		return result
	}

	prompt := fmt.Sprintf(`You are implementing an improvement to VXD (an AI agent orchestration CLI tool in Go).

Finding: %s
Source: %s
Implementation Plan: %s
Test Strategy: %s

RULES:
- Implement exactly what the plan describes
- Write tests for your changes
- Do NOT modify files outside the scope described
- Do NOT add unnecessary dependencies
- Commit all changes with a descriptive message

Work in the current directory.`, finding.Title, finding.SourceURL, finding.ImplementationPlan, finding.TestStrategy)

	cmd := exec.CommandContext(ctx, impl.claudePath, "-p", prompt, "--output-format", "json", "--max-turns", "1")
	cmd.Dir = impl.repoPath
	output, err := cmd.CombinedOutput()
	if err != nil {
		log.Printf("[implementer] claude failed for %q: %v\nOutput: %s", finding.Title, err, string(output))
		result.Disposition = "aborted"
		result.Error = fmt.Sprintf("claude: %v", err)
		impl.git("checkout", "main")
		impl.git("branch", "-D", branch)
		return result
	}

	gates := []struct {
		name string
		fn   func() error
	}{
		{"build", func() error { return impl.run("go", "build", "./...") }},
		{"vet", func() error { return impl.run("go", "vet", "./...") }},
		{"test", func() error { return impl.run("go", "test", "-race", "./...") }},
		{"diff-size", func() error {
			diff, _ := impl.gitOutput("diff", "main...HEAD")
			return CheckDiffSize(diff, impl.maxDiff)
		}},
		{"file-count", func() error {
			stat, _ := impl.gitOutput("diff", "--shortstat", "main...HEAD")
			return CheckFileCount(stat, impl.maxFiles)
		}},
		{"secrets", func() error {
			diff, _ := impl.gitOutput("diff", "main...HEAD")
			return CheckSecrets(diff)
		}},
	}

	for _, gate := range gates {
		if err := gate.fn(); err != nil {
			log.Printf("[implementer] gate %q failed for %q: %v", gate.name, finding.Title, err)
			result.Disposition = "aborted"
			result.Error = fmt.Sprintf("gate %s: %v", gate.name, err)
			impl.git("checkout", "main")
			impl.git("branch", "-D", branch)
			return result
		}
	}

	result.TestsPassed = true

	stat, _ := impl.gitOutput("diff", "--shortstat", "main...HEAD")
	result.FilesChanged, result.LinesChanged = parseDiffStat(stat)

	if err := impl.git("push", "-u", "origin", branch); err != nil {
		result.Disposition = "aborted"
		result.Error = fmt.Sprintf("push: %v", err)
		return result
	}

	prBody := fmt.Sprintf("## Auto-Improvement\n\n**Source:** %s\n**Category:** %s\n**Reasoning:** %s\n\n**Security Review:** %s\n**License Check:** %s\n\n---\n*Generated by VXD Self-Improvement Engine*",
		finding.SourceURL, finding.Category, finding.Reasoning, finding.SecurityReview, finding.LicenseCheck)

	prURL, err := impl.createPR(finding.Title, prBody, branch)
	if err != nil {
		result.Disposition = "aborted"
		result.Error = fmt.Sprintf("create PR: %v", err)
		return result
	}

	result.PRURL = prURL
	result.Disposition = "implemented"
	impl.git("checkout", "main")

	return result
}

func (impl *Implementer) git(args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = impl.repoPath
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, string(out))
	}
	return nil
}

func (impl *Implementer) gitOutput(args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = impl.repoPath
	out, err := cmd.Output()
	return strings.TrimSpace(string(out)), err
}

func (impl *Implementer) run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = impl.repoPath
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, string(out))
	}
	return nil
}

func (impl *Implementer) createPR(title, body, branch string) (string, error) {
	cmd := exec.Command("gh", "pr", "create", "--title", title, "--body", body, "--base", "main", "--head", branch)
	cmd.Dir = impl.repoPath
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("gh pr create: %s", string(out))
	}
	return strings.TrimSpace(string(out)), nil
}

// CheckDiffSize verifies the diff doesn't exceed the line limit.
func CheckDiffSize(diff string, maxLines int) error {
	lines := strings.Count(diff, "\n")
	if lines > maxLines {
		return fmt.Errorf("diff too large: %d lines (max %d)", lines, maxLines)
	}
	return nil
}

// CheckFileCount verifies the number of changed files doesn't exceed the limit.
func CheckFileCount(shortstat string, maxFiles int) error {
	re := regexp.MustCompile(`(\d+)\s+files?\s+changed`)
	matches := re.FindStringSubmatch(shortstat)
	if len(matches) < 2 {
		return nil
	}
	count, _ := strconv.Atoi(matches[1])
	if count > maxFiles {
		return fmt.Errorf("too many files changed: %d (max %d)", count, maxFiles)
	}
	return nil
}

// CheckSecrets scans a diff for hardcoded secrets.
func CheckSecrets(diff string) error {
	if ScanForSecrets(diff) {
		return fmt.Errorf("potential secret detected in diff")
	}
	return nil
}

func slugify(s string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9]+`)
	slug := re.ReplaceAllString(strings.ToLower(s), "-")
	if len(slug) > 50 {
		slug = slug[:50]
	}
	return strings.Trim(slug, "-")
}

func parseDiffStat(stat string) (files, lines int) {
	re := regexp.MustCompile(`(\d+)\s+files?\s+changed`)
	if m := re.FindStringSubmatch(stat); len(m) >= 2 {
		files, _ = strconv.Atoi(m[1])
	}
	insertRe := regexp.MustCompile(`(\d+)\s+insertions?`)
	deleteRe := regexp.MustCompile(`(\d+)\s+deletions?`)
	if m := insertRe.FindStringSubmatch(stat); len(m) >= 2 {
		n, _ := strconv.Atoi(m[1])
		lines += n
	}
	if m := deleteRe.FindStringSubmatch(stat); len(m) >= 2 {
		n, _ := strconv.Atoi(m[1])
		lines += n
	}
	return
}
