package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// DefaultConfig returns a Config populated with sensible defaults.
// The returned value passes Validate() without modification.
func DefaultConfig() Config {
	return Config{
		Version: "1.0",
		Workspace: WorkspaceConfig{
			StateDir:         "~/.vxd",
			Backend:          "dolt",
			LogLevel:         "info",
			LogRetentionDays: 30,
		},
		Models: ModelsConfig{
			TechLead:     ModelConfig{Provider: "anthropic", Model: "claude-opus-4-6-20250620", MaxTokens: 16000},
			Senior:       ModelConfig{Provider: "anthropic", Model: "claude-sonnet-4-6-20250620", MaxTokens: 8000},
			Intermediate: ModelConfig{Provider: "google", Model: "gemma-4-27b-it", MaxTokens: 4000},
			Junior:       ModelConfig{Provider: "google", Model: "gemma-4-27b-it", MaxTokens: 4000},
			QA:           ModelConfig{Provider: "anthropic", Model: "claude-sonnet-4-6-20250620", MaxTokens: 8000},
			Supervisor:   ModelConfig{Provider: "google", Model: "gemma-4-27b-it", MaxTokens: 4000},
			Manager:      ModelConfig{Provider: "anthropic", Model: "claude-sonnet-4-6-20250620", MaxTokens: 8000},
		},
		Routing: RoutingConfig{
			JuniorMaxComplexity:           3,
			IntermediateMaxComplexity:     5,
			MaxRetriesBeforeEscalation:    2,
			MaxQAFailuresBeforeEscalation: 3,
			MaxSeniorRetries:              2,
			MaxManagerAttempts:            2,
			MaxConcurrentAgents:           5,
		},
		Monitor: MonitorConfig{
			PollIntervalMs:         10000,
			StuckThresholdS:        120,
			ContextFreshnessTokens: 150000,
		},
		Cleanup: CleanupConfig{
			WorktreePrune:       "immediate",
			BranchRetentionDays: 7,
			LogArchive:          "dolt",
		},
		Merge: MergeConfig{
			AutoMerge:  true,
			BaseBranch: "main",
			PRTemplate: "## Story: {story_id}\n{description}\n### Acceptance Criteria\n{acceptance_criteria}\n",
		},
		Planning: PlanningConfig{
			SequentialFilePatterns: []string{"package.json", "*.config.*", "src/core/*"},
			MaxStoryComplexity:     5,
		},
		Billing: BillingConfig{
			DefaultRate: 150.0,
			Currency:    "USD",
			HoursPerPoint: map[int][2]float64{
				1:  {0.5, 1.0},
				2:  {1.0, 2.0},
				3:  {2.0, 3.0},
				5:  {3.0, 5.0},
				8:  {5.0, 8.0},
				13: {8.0, 13.0},
			},
			LLMCosts: LLMCostConfig{
				Mode: "subscription",
			},
		},
		Runtimes: map[string]RuntimeConfig{
			"claude-code": {
				Command: "claude",
				Args:    []string{"--dangerously-skip-permissions"},
				Models:  []string{"opus-4-6", "sonnet-4-6", "haiku-4-5"},
				Detection: RuntimeDetection{
					IdlePattern:       `^\$\s*$`,
					PermissionPattern: `\[Y/n\]`,
					PlanModePattern:   "Plan mode",
				},
			},
			"codex": {
				Command: "codex",
				Args:    []string{"--approval-mode", "full-auto"},
				Models:  []string{"o3", "o4-mini"},
				Detection: RuntimeDetection{
					IdlePattern:       "Codex>",
					PermissionPattern: "approve|deny",
				},
			},
			"gemini": {
				Command: "gemini",
				Args:    []string{"--sandbox"},
				Models:  []string{"gemini-2.5-pro", "gemini-2.5-flash"},
				Detection: RuntimeDetection{
					IdlePattern:       "gemini>",
					PermissionPattern: "Allow|Deny",
				},
			},
			"swe-agent": {
				Command: "swe-agent",
				Args:    []string{"run", "--agent.model.name"},
				Models:  []string{"gpt-4o", "claude-sonnet-4-6-20250620"},
				Detection: RuntimeDetection{
					IdlePattern:       "SWE-agent>",
					PermissionPattern: "confirm|cancel",
				},
			},
		},
		SLA: SLAConfig{
			MaxMinutesPerComplexity: map[int]int{
				1:  60,   // 1hr
				2:  120,  // 2hr
				3:  240,  // 4hr
				5:  480,  // 8hr
				8:  960,  // 16hr
				13: 1920, // 32hr
			},
		},
	}
}

// DefaultYAML marshals DefaultConfig to YAML bytes suitable for writing
// as a vxd.yaml configuration file.
func DefaultYAML() ([]byte, error) {
	cfg := DefaultConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshalling default config: %w", err)
	}

	header := []byte("# VXD configuration — generated by 'vxd init'\n" +
		"# See https://github.com/tzone85/vortex-dispatch for documentation.\n\n")
	return append(header, data...), nil
}

// LoadFromFile reads a YAML configuration file, overlays it on top of
// DefaultConfig (so unset fields keep their defaults), validates, and
// returns the result.
func LoadFromFile(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("reading config file: %w", err)
	}

	cfg := DefaultConfig()

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("parsing config YAML: %w", err)
	}

	if err := cfg.Validate(); err != nil {
		return Config{}, fmt.Errorf("config validation: %w", err)
	}

	return cfg, nil
}

// LoadConfigChain tries to load configuration from a chain of sources:
//  1. repoPath -- per-project vxd.yaml in the repo root (highest priority)
//  2. globalPath -- global ~/.vxd/config.yaml (fallback defaults)
//  3. DefaultConfig() -- hardcoded fallback
//
// Returns the first successfully loaded config. If all files are missing,
// returns DefaultConfig() without error. Only returns an error if a file
// exists but is malformed.
func LoadConfigChain(repoPath, globalPath string) (Config, error) {
	// Try repo config first
	cfg, err := LoadFromFile(repoPath)
	if err == nil {
		return cfg, nil
	}
	// If file exists but is malformed, return that error
	if _, statErr := os.Stat(repoPath); statErr == nil {
		return Config{}, err
	}

	// Try global config
	cfg, err = LoadFromFile(globalPath)
	if err == nil {
		return cfg, nil
	}
	if _, statErr := os.Stat(globalPath); statErr == nil {
		return Config{}, err
	}

	// Fall back to defaults
	return DefaultConfig(), nil
}
